### ISSUE TITLE
Would be great also to have a vw2libsvm converter

### ISSUE THREAD

**Issue by kirillfish** [zygmuntz/phraug2#10]
There is already a libsvm2vw, but sometimes the opposite way (from vw to libsvm and to other formats) is also needed. Suppose I've tried out vowpal wabbit on some dataset, and then decided to learn xgboost on the same dataset. Then having such converter would be very helpful, because xgboost can work with libsvm format directly.

**Comment by zygmuntz** [comment]
In the most basic case conversion from VW to libsvm only entails removing "|namespacename" between the label and the rest of the row. Generally, I think that one first converts to VW from some other format like CSV, so CSV to libsvm would do the trick.

**Comment by kirillfish** [comment]
Not only to remove namespace names, but also to appending them to feature names, i.e. `namespacename^featurename:1`
