### ISSUE TITLE
Would be great if there was sparsematrix2vw

### ISSUE THREAD

**Issue by jeffwong** [zygmuntz/phraug2#8]
I would love to see a way someone can convert a R data frame into VW input. I think for really large data where someone would want to use VW in the first place, to write out the R data frame would be overkill. Chances are the data would be sparse, so a generic sparsematrix2vw would be great!

**Comment by zygmuntz** [comment]
You could write _libsvm_ file from R and then use `libsvm2vw.py`. Or even modify the "write libsvm" script to output VW format, it's very close (just an additional `|namespace_name` after a label.
